language: python
python:
  - "2.7"
env:
  - DV=1.5.1 CV=1.2.1
  - DV=1.5.1 CV=1.2.2
  - DV=1.5.1 CV=1.2.2
  - DV=1.6.11 CV=1.2.2
  - DV=1.7.8 CV=1.3b1
install:
  - pip install django-categories==$CV
  - pip install Django==$DV
  - pip install -e .
  - pip install BeautifulSoup django-staticfiles south
script:
  - ./run_tests.sh
notifications:
  email:
    - ci@callowayproject.com